djangoAjaxLogin/apps/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('home/', views.Home.as_view(), name='home'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

djangoAjaxLogin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djangoAjaxLogin.apps.core.urls')),
]

djangoAjaxLogin/apps/core/models.py
from django.db import models

# Create your models here.

djangoAjaxLogin/apps/core/views.py
import json

from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http.response import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Q


# Create your views here.
class Index(TemplateView):
    http_method_names = ['get']
    template_name = 'core/index.html'


class Login(LoginView):
    http_method_names = ['get', 'post']
    template_name = 'core/login.html'

    def get(self, request, *args, **kwargs):
        if 'search' in request.GET:
            data = None
            status = None

            search = request.GET['search']

            try:
                query = (
                    Q(username=search) |
                    Q(email=search)
                )
                user = User.objects.get(query)
                data = {'username': user.username}
                status = 200
            except User.DoesNotExist:
                data = {'error': 'User does not exist'}
                status = 404

            return JsonResponse(data, safe=False, status=status)

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = None
        status = None

        form = self.form_class(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                login(request, user)
                data = {'success': True}
                status = 200

        else:
            data = json.dumps(dict(form.errors.items()), ensure_ascii=False)
            status = 401

        return JsonResponse(data, safe=False, status=status)


class Home(LoginRequiredMixin, TemplateView):
    http_method_names = ['get']
    template_name = 'core/home.html'

    def get_login_url(self):
        return reverse('core:login')


class Logout(LogoutView):
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('core:index'))

djangoAjaxLogin/apps/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

    {# extra styles #}
    {% block css %}
    {% endblock %}

    <title>Ajax Login with Django!</title>
  </head>
  <body>
    <div class="container">
      <br>
      <h1 class="text-center">Django Ajax Login</h1>
      {% block content %}
      {% endblock %}
    </div>

    <footer class="py-2 bg-dark text-white-50 fixed-bottom">
      <div class="container text-center">
        <small>Apache License 2.0 | developed by
          <a href="https://devlance.me" target="_blank">Devlance.me</a>
        </small>
      </div>
    </footer>

    <script src="{% static 'core/js/jquery-3.3.1-slim.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'core/js/axios.min.js' %}"></script>
	
	<!--For IE to work with promises-->
	<script src="https://cdn.polyfill.io/v3/polyfill.min.js"></script>
	<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/js-polyfills/0.1.42/polyfill.min.js"></script>-->

    {# extra scripts #}
    {% block js %}
    {% endblock %}

  </body>
</html>

djangoAjaxLogin/apps/core/templates/core/home.html
{% extends 'core/base.html' %}


{% block content %}
      <h4 class="text-center">Django Application for handling Login with Ajax and Class-Based Views.</h4>
      <br>
      <ul class="list-group">
        <li class="list-group-item list-group-item-primary">
          You are logged in {{ request.user.username }}!
        </li>
        <li class="list-group-item list-group-item-primary">
          Your email is: {{ request.user.email }}
        </li>
        <li class="list-group-item list-group-item-primary">
          click in 'logout' to sign-out
        </li>
      </ul>
      <br>
      <h4 class="text-center">Menu:</h4>

      <div class="list-group">
        <a href="{% url 'core:logout' %}" class="list-group-item list-group-item-action list-group-item-danger text-center">Logout</a>
      </div>
{% endblock %}

djangoAjaxLogin/apps/core/templates/core/index.html
{% extends 'core/base.html' %}


{% block content %}
      <h4 class="text-center">Django Application for handling Login with Ajax and Class-Based Views.</h4>
      <br>
      <ul class="list-group">
        <li class="list-group-item list-group-item-info">
          click in 'login' to sign-in
        </li>
        <li class="list-group-item list-group-item-info">
          click in 'home' to go to home's user
        </li>
      </ul>
      <br>
      <h4 class="text-center">Menu:</h4>

      <div class="list-group">
        <a href="{% url 'core:login' %}" class="list-group-item list-group-item-action text-center">Login</a>
        <a href="{% url 'core:home' %}" class="list-group-item list-group-item-action text-center">Home</a>
      </div>
{% endblock %}

djangoAjaxLogin/apps/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
      <div class="alert alert-danger" id="alertErrors" hidden="true" role="alert"></div>
      <br>
      <form id="searchForm" onsubmit="event.preventDefault();">
        <div class="form-group">
          <label for="search">User</label>
          <input type="text" class="form-control" id="search" name="search" placeholder="Enter username or email">
        </div>
        <button type="submit" id="submit" class="btn btn-primary">Search User</button>
        <a href="{% url 'core:index' %}" class="btn btn-secondary">Back</a>
      </form>

      <form id="loginForm" hidden="true" onsubmit="event.preventDefault();">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" class="form-control" disabled="true" id="username" name="username" placeholder="Enter username or email">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" autofocus="true" id="password" name="password" placeholder="Enter password">
        </div>
        <button type="submit" id="submit" class="btn btn-success">Login</button>
        <a href="{% url 'core:login' %}" class="btn btn-info">Change User</a>
      </form>
{% endblock %}

{% block js %}
    <script>
      var searchForm = $('#searchForm');
      var search = $('#search');
      var submit = searchForm.children('button');
      var alertErrors = $('#alertErrors');

      submit.click(function(e){
        
        if (search.val() !== '') {
          submit.attr('disabled', true);

          axios({
            method: 'get',
            url: '{% url "core:login" %}?search=' + search.val(),
            headers: {
              'cache-control':  'no-cache',
              'content-type':   'application/x-www-form-urlencoded'
              }
          })
          .then(function (response) {
            if (response.status === 200) {
              var username = response.data['username'];
              alertErrors.html('');
              alertErrors.attr('hidden', true);
              searchForm.attr('hidden', true);
              $('#username').val(username);
              $('#loginForm').removeAttr('hidden');
              submit.removeAttr('disabled');
            }
          })
          .catch(function (error) {
            var err = error.response.data['error'];
            alertErrors.html('');
            var strError = '<p>Error: ' + err + '</p>';
            alertErrors.html(strError);
            alertErrors.removeAttr('hidden');
            submit.removeAttr('disabled');
          });
        }
        
      });
    </script>
    <script>
      var loginForm = $('#loginForm');
      var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]');
      var username = $('#username');
      var password = $('#password');
      var submit = loginForm.children('button');
      var alertErrors = $('#alertErrors');

      submit.click(function (e){
        if (password.val() !== '') {
          submit.attr('disabled', true);

          var data = new URLSearchParams();
          data.append('csrfmiddlewaretoken', csrfmiddlewaretoken.val());
          data.append('username', username.val());
          data.append('password', password.val());

          axios({
            method: 'post',
            url: '{% url "core:login" %}',
            data: data,
            xsrfCookieName: 'csrftoken',
            xsrfHeaderName: 'X-CSRFToken',
            headers: {
              'cache-control':  'no-cache',
              'content-type':   'application/x-www-form-urlencoded'
              }
          })
          .then(function (response) {
            if (response.status === 200) {
              alertErrors.attr('hidden', 'true');
              window.location.replace('{% url "core:home" %}');
            }
          })
          .catch(function (error) {
            alertErrors.html('');
            var strError = '';
            var errors = JSON.parse(error.response.data);

            for (var err in errors) {
              for (var e in errors[err]) {
                strError += '<p>' + errors[err][e] + '</p>';
              }

            }
            alertErrors.html(strError);
            alertErrors.removeAttr('hidden');
            submit.removeAttr('disabled');
          });

        }
      });
    </script>
{% endblock %}
    